name: Auto-update from PyPI

on:
  schedule:
    # Check for updates daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check for new version
        id: check_version
        run: |
          # Get current version from manifest
          CURRENT_VERSION=$(python -c "import json; print(json.load(open('bucket/rxiv-maker.json'))['version'])")
          echo "Current version: $CURRENT_VERSION"
          
          # Get latest version from PyPI
          LATEST_VERSION=$(curl -s "https://pypi.org/pypi/rxiv-maker/json" | python -c "import sys, json; print(json.load(sys.stdin)['info']['version'])")
          echo "Latest version: $LATEST_VERSION"
          
          # Compare versions
          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
            echo "New version available: $LATEST_VERSION"
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "new_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
            echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "No update needed"
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Update manifest
        if: steps.check_version.outputs.update_needed == 'true'
        run: |
          NEW_VERSION="${{ steps.check_version.outputs.new_version }}"
          
          # Get SHA256 hash from PyPI
          SHA256=$(curl -s "https://pypi.org/pypi/rxiv-maker/json" | \
                  python -c "
          import sys, json, os
          data = json.load(sys.stdin)
          new_version = os.environ.get('NEW_VERSION')
          for file_info in data['releases'][new_version]:
              if file_info['packagetype'] == 'sdist':
                  print(file_info['digests']['sha256'])
                  break
          " )
          
          echo "New SHA256: $SHA256"
          
          # Update manifest
          python -c "
          import json, os
          
          new_version = os.environ.get('NEW_VERSION')
          sha256 = os.environ.get('SHA256')
          
          with open('bucket/rxiv-maker.json', 'r') as f:
              manifest = json.load(f)
          
          manifest['version'] = new_version
          manifest['url'] = f'https://files.pythonhosted.org/packages/source/r/rxiv-maker/rxiv_maker-{new_version}.tar.gz'
          manifest['hash'] = f'sha256:{sha256}'
          
          with open('bucket/rxiv-maker.json', 'w') as f:
              json.dump(manifest, f, indent=4)
          "
          
      - name: Test updated manifest
        if: steps.check_version.outputs.update_needed == 'true'
        run: |
          # Validate JSON syntax
          python -m json.tool bucket/rxiv-maker.json > /dev/null
          echo "JSON syntax is valid"
          
          # Verify download URL
          NEW_VERSION="${{ steps.check_version.outputs.new_version }}"
          URL="https://files.pythonhosted.org/packages/source/r/rxiv-maker/rxiv_maker-$NEW_VERSION.tar.gz"
          curl -I -f "$URL"
          echo "Download URL is valid"
          
      - name: Create Pull Request
        if: steps.check_version.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update rxiv-maker to version ${{ steps.check_version.outputs.new_version }}"
          title: "Auto-update: rxiv-maker ${{ steps.check_version.outputs.current_version }} → ${{ steps.check_version.outputs.new_version }}"
          body: |
            ## Auto-update from PyPI
            
            **Previous version:** `${{ steps.check_version.outputs.current_version }}`
            **New version:** `${{ steps.check_version.outputs.new_version }}`
            
            ### Changes
            - Updated version number in manifest
            - Updated download URL
            - Updated SHA256 checksum
            
            ### Verification
            - [x] JSON syntax validated
            - [x] Download URL verified
            - [ ] Manual testing (pending review)
            
            **PyPI Release:** https://pypi.org/project/rxiv-maker/${{ steps.check_version.outputs.new_version }}/
            
            This PR was automatically created by the update workflow.
          branch: auto-update-${{ steps.check_version.outputs.new_version }}
          delete-branch: true
          
      - name: Auto-merge if tests pass
        if: steps.check_version.outputs.update_needed == 'true'
        uses: pascalgn/merge-action@v0.15.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          merge_labels: "auto-update,dependencies"